### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jbojcic1** [bonjurmrfirst/angular4-carousel#20] opened 2017-09-18 12:13 UTC
I followed installation steps and I am getting the following error:

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /.../node_modules/angular4-carousel/node_modules/@angular/core/core.d.ts, resolving symbol CarouselModule in /.../node_modules/angular4-carousel/src/app/index.ts, resolving symbol CarouselModule in /.../node_modules/angular4-carousel/src/app/index.ts

Am I doing something wrong or there is a bug?

**Comment by dockleryxk** [comment] 2017-09-22 15:22
I am no longer supporting this package, perhaps @bonjurmrfirst will. If not you can check out [this slideshow](https://github.com/dockleryxk/ng-simple-slideshow) I will be supporting

**Comment by jbojcic1** [comment] 2017-09-22 19:23
Ok. Will check it out. Thx

**Comment by bonjurmrfirst** [comment] 2017-09-27 10:22
Hi,
can't reproduce an error

**Comment by bonjurmrfirst** [comment] 2017-09-27 10:47
@dockleryxk, thx for supporting, I appreciate

**Comment by kapr1k0rn** [comment] 2017-09-28 03:13
@bonjurmrfirst Hi,
I am getting the same error. To reproduce the error,
1.ng new carousel
2.npm install angular4-carousel --save
3.import module and write some code to use carousel in app.component.

**Comment by bonjurmrfirst** [comment] 2017-09-28 07:40
Hi, @kapr1k0rn 
Looks like issue resolved by updating cli.

Closed.

**Closed by bonjurmrfirst** 2017-09-28 07:40 UTC

**Comment by MohitKS5** [comment] 2017-12-08 16:21
same error in angular 1.6.0

**Comment by HKSultan** [comment] 2018-03-29 07:42
same error in angular cli 1.7.3
